config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.json { render json: @kittens }
      format.html
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.json { render json: @kitten }
      format.html
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to root_path, notice: "You've created a new cat with success!"
    else
      flash.now[:alert] = "Something went wrong, please try do it again."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to root_path, notice: "The kitten has been updated with success!"
    else
      flash.now[:alert] = "Something went wrong! Try do it again."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])

    if @kitten.destroy
      redirect_to root_path, notice: "That kitten has been deleted with success."
    end

  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<%= form_with model: @kitten, html: { style: 'padding 1rem; border: 1.5px solid black;' } do |form| %>
  <div class="field" style="padding: 0.25rem;">
    <%= form.label :name, style: 'display: block;' %>
    <%= form.text_field :name, placeholder: "Cat's name" %>
  </div>

  <div class="field" style="padding: 0.25rem;">
    <%= form.label :age, style: 'display: block;' %>
    <%= form.number_field :age %>
  </div>

  <div class="field" style="padding: 0.25rem;">
    <%= form.label :cuteness, style: 'display: block;' %>
    <%= form.number_field :cuteness %>
  </div>

  <div class="field" style="padding: 0.25rem;">
    <%= form.label :softness, style: 'display: block;' %>
    <%= form.number_field :cuteness %>
  </div>

  <%= form.submit 'Save that changes!', style: "margin: 0.25rem; cursor: pointer;" %>
<% end %>

app/views/kittens/index.html.erb
<div style="padding: 0.5rem;">
  <% @kittens.each do |kitten| %>
    <article class="kitten-information-container" style="margin-bottom: 4px; border: 1px solid black; padding: 0.5rem; display: flex; gap: 8px; align-items: center;">
      <%= button_to 'E', edit_kitten_path(kitten), method: :get, style: "cursor: pointer; padding: 4px;" %>
      <%= button_to 'X', kitten_path(kitten), method: :delete, style: "cursor: pointer; padding: 4px; background-color: red; color: white; border: 2px solid darkred; border-radius: 2px;" %>
      <%= link_to kitten_path(kitten), style: 'text-decoration: none;' do %>
        <span><%= kitten.id %> / <%= kitten.name %></span>
      <% end %>
    </article>
  <% end %>
</div>

app/views/kittens/new.html.erb
<%= form_with model: @kitten, html: { style: 'padding 1rem; border: 1.5px solid black;' } do |form| %>
  <div class="field" style="padding: 0.25rem;">
    <%= form.label :name, style: 'display: block;' %>
    <%= form.text_field :name, placeholder: "Cat's name" %>
  </div>

  <div class="field" style="padding: 0.25rem;">
    <%= form.label :age, style: 'display: block;' %>
    <%= form.number_field :age %>
  </div>

  <div class="field" style="padding: 0.25rem;">
    <%= form.label :cuteness, style: 'display: block;' %>
    <%= form.number_field :cuteness %>
  </div>

  <div class="field" style="padding: 0.25rem;">
    <%= form.label :softness, style: 'display: block;' %>
    <%= form.number_field :softness %>
  </div>

  <%= form.submit 'Create a cat', style: "margin: 0.25rem; cursor: pointer;" %>
<% end %>

app/views/kittens/show.html.erb
<article style="width: 100vw; height: 100vh; display: flex; align-items: center; justify-content: center;">
  <div style="display: flex; flex-direction: column; gap: 4px; padding: 2rem; border: 1px solid black;">
    <span>ID: <%= @kitten.id %></span>
    <span>Name: <%= @kitten.name %></span>
    <span>Age: <%= @kitten.age %></span>
    <span>Cuteness: <%= @kitten.cuteness %></span>
    <span>Softness: <%= @kitten.softness %></span>
    <%= link_to 'Go back', root_path %>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div style="width: 100%; background-color: green;">
        <p style="color: white; padding: 1rem;"><%= flash[:notice] %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div style="width: 100%; background-color: gold;">
        <p style="color: black; padding: 1rem;"><%= flash[:alert] %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>